### ISSUE TITLE
Deliver Blog:  Tekton, learn about Kabanero's DevOps Toolchain

### ISSUE THREAD

**Issue by nateziemann** [kabanero-io/blogs#15]
As part of the August 26th release blog series, we want to introduce Tekton and our Kabanero DevOps Toolchain. The goal is to build momentum through our blog series from August 26 release up to the September events that begin Sept 9th and run through Sept 26.

This blog should describe why we chose Tekton, what it’s good at, how we are using Tekton, the DevOps flow for a team in Kabanero.(webhooks that listen for git events (commit, review, merge).  Describe the different tasks we are building and how Champ can customize build and deploy pipelines.

We should talk about how we're contributing back to the Tekton community and pulling that back into Kabanero.

Given where we're at, I'd like this to be a little forward looking, so need Alan & Steve's views on exactly what we're doing in the very near future ....  introducing an event/notification subsystem to enable a full end-to-end automated Toolchain that can support Tekton pipelines and alternatives like Jenkins.  Replacing webhooks w/ our new eventing subsystem, what we're doing with Razee to tag and drive automated promotion to production clusters, etc.

**Comment by nateziemann** [comment]
Alan, Steve, Mark N & Michael Cheng should all be involved in crafting this blog imho.  Anita and John D should be reviewers / contributors as well. Given my interest in the future aspects I'd like to review the forward looking messaging. 

Assigned Author(s):
Reviewer(s):
Target:  Sept 4-6. Definitely ahead of John/Mark's Sept 12 Summit session.

**Comment by nateziemann** [comment]
I can't find Anita, John, Mark in our Kabanero repos to add as possible assignees.

**Comment by alohr51** [comment]
Is there a blog post available that needs to go out for this?

**Comment by marikaj123** [comment]
Is this going into Oct-7?

**Comment by stephenkinder** [comment]
@marikaj123 In terms of timing, I think there are other high priority blogs that need to happen for Oct 7.  As far as Tekton and Kabanero collections, I'd like to be able to wire repositories to multiple pipelines and simplify the webhook creation.   Suggest we target the planned `0.3.0` release, as we are hoping to have a preliminary solution for events.

**Comment by dianak2016** [comment]
@rasswann is the main owner of this blog issue.  She has broken up the original blog request into a series of blogs that will be published over time.  The first in the series is an intro to Tekton covering why you would use it and the value it adds.  This is targeted for October.  Remaining topics in the series include an intro: architecture (Nov), example, use in Kabanero, Dashboard, and Triggers.  Anita will keep this issue updated with progress/changes.

**Comment by Charlotte-Holt** [comment]
@anneqm and I met today to work through edits for the October Tekton blog post.

**Comment by anneqm** [comment]
Thanks @dewan-ahmed for creating the PR for the initial blog, written by @rasswan and John Duimovich.  It is located here:  https://github.com/kabanero-io/blogs/pull/25
Who else needs to review?  @nateziemann, @stephenkinder ?
