### ISSUE TITLE
Blog:  Promote upcoming events Kabanero will be present at

### ISSUE THREAD

**Issue by nateziemann** [kabanero-io/blogs#16]
Include events for September that Kabanero will attending and featured:   Hurlsey Summit, Code One, and Chicago Summit.

Erin Heximer will provide input and promotion for the two summits.  I want the messaging to be around events you can learn more about Kabanero and open technologies integrated by Kabanero.  See session xyz for Intro to Kabanero.  Session abc for DevOps practices with new open technologies native for Kubernetes.  Session zyx for new open source developer tools that simplify developing cloud native apps for kuberentes and in containers within popular IDE workflows.

At CodeOne we have a ped at the IBM Booth.  Come find us at the Kabanero ped within IBM's expo presence to learn more, see it in action and interact with experts.  Erin Schnabel is doing a session that will include Kabanero.  Get the session number and URL link to promote that as well.

**Comment by erpenbach** [comment]
Completed under https://github.com/erpenbach/blogs/pull/3

**Comment by alohr51** [comment]
this went live on https://kabanero.io/blog/ august 30th
