### ISSUE TITLE
Blog:  Part 2 in series on Tekton, learn about Kabanero's DevOps Toolchain: Tekton Architecture 

### ISSUE THREAD

**Issue by anneqm** [kabanero-io/blogs#32]
Blog Title: "Cloud-Native Devops: Tekton Architecture and Design"

Draft Blog by Mark Nuttall, is located at this PR: https://github.com/kabanero-io/blogs/pull/31

**Comment by nateziemann** [comment]
This blog is too generic and open source about Tekton.  This blog should be re-organized to focus on the exact architecture and detailed pipelines that are included in Kabanero and the Integrated DevOps value users get from Kabanero as an open source project that is the upstream for IBM Cloud Pak for Applications, given that's the purpose of this blog.  Don't get me wrong, the technical content looks considerably valuable but in the current form belongs on a Tekton or CD Foundation blog.   

 It needs to lead w/ Kabanero in the title and in the beginning of the blog including the value Tekton brings for DevOps into Kabanero, the types of tasks and pipeline(s) we include in 0.3, then get into more general architectural of Tekton itself, then promote the guides  section to learn more including new pipelines guide that we should publish in parallel to this blog.

@mnuttall I'm copying @tseelbach who's been working on the pipelines themselves to help feed more unique Kabanero text into the blog however you see best.

**Comment by anneqm** [comment]
This Blog will be published on developer.ibm.com and is being tracked with this issue: 
https://github.ibm.com/IBMCode/IBMCodeContent/issues/3578. Will add link to published blog when available and will close this issue at this time.

**Comment by anneqm** [comment]
This blog has now been published on developer.ibm.com and is available at https://developer.ibm.com/articles/introduction-to-tekton-architecture-and-design
