### ISSUE TITLE
Deliver a release announce Blog - Oct 7th- What's new

### ISSUE THREAD

**Issue by nateziemann** [kabanero-io/blogs#9]
Promote the August 26th release through a release announce blog describing what's new and how to try it.

Owner:  Stephen Kinder
Reviewer: Nate Ziemann

**Comment by stephenkinder** [comment]
@garypicher let's work on the Oct 7th -- "What is New?" story for the 0.2.0 release.  Minimally, we need to commit to the kabanero-foundation release documentation in Github.

**Comment by marikaj123** [comment]
Steve is working on what's new for the release. Deliver during rc release. No ID is required

**Comment by stephenkinder** [comment]
[Whats-new-0.2.0.docx](https://github.com/kabanero-io/blogs/files/3748065/Whats-new-0.2.0.docx) @alohr51 @jantley-ibm - proposed blog.  Needs review and someplace to publish; can you please provide assistance?

**Comment by dionj** [comment]
@nateziemann @dianak2016 @erpenbach please review @stephenkinder blogs before he can publish it.  Thank you.

**Comment by dianak2016** [comment]
Blog is complete: https://kabanero.io/blog/2019/10/20/WhatsNew020.html

**Comment by dionj** [comment]
Multiple Tweets about the new release v0.2.0 have been tweeted out from KabaneroIO twitter account.
